#pragma once
#ifndef REPEAT_MACRO_HH_
# define REPEAT_MACRO_HH_


# define REPEAT(n, maccro, data) REPEAT##n(maccro, data)

# define REPEAT1(macro, data)   macro(1, data)
# define REPEAT2(macro, data)   macro(2, data)  REPEAT1(macro, data)
# define REPEAT3(macro, data)   macro(3, data)  REPEAT2(macro, data)
# define REPEAT4(macro, data)   macro(4, data)  REPEAT3(macro, data)
# define REPEAT5(macro, data)   macro(5, data)  REPEAT4(macro, data)
# define REPEAT6(macro, data)   macro(6, data)  REPEAT5(macro, data)
# define REPEAT7(macro, data)   macro(7, data)  REPEAT6(macro, data)
# define REPEAT8(macro, data)   macro(8, data)  REPEAT7(macro, data)
# define REPEAT9(macro, data)   macro(9, data)  REPEAT8(macro, data)
# define REPEAT10(macro, data)  macro(10, data) REPEAT9(macro, data)
# define REPEAT11(macro, data)  macro(11, data) REPEAT10(macro, data)
# define REPEAT12(macro, data)  macro(12, data) REPEAT11(macro, data)
# define REPEAT13(macro, data)  macro(13, data) REPEAT12(macro, data)
# define REPEAT14(macro, data)  macro(14, data) REPEAT13(macro, data)
# define REPEAT15(macro, data)  macro(15, data) REPEAT14(macro, data)
# define REPEAT16(macro, data)  macro(16, data) REPEAT15(macro, data)
# define REPEAT17(macro, data)  macro(17, data) REPEAT16(macro, data)
# define REPEAT18(macro, data)  macro(18, data) REPEAT17(macro, data)
# define REPEAT19(macro, data)  macro(19, data) REPEAT18(macro, data)
# define REPEAT20(macro, data)  macro(20, data) REPEAT19(macro, data)
# define REPEAT21(macro, data)  macro(21, data) REPEAT20(macro, data)
# define REPEAT22(macro, data)  macro(22, data) REPEAT21(macro, data)
# define REPEAT23(macro, data)  macro(23, data) REPEAT22(macro, data)
# define REPEAT24(macro, data)  macro(24, data) REPEAT23(macro, data)
# define REPEAT25(macro, data)  macro(25, data) REPEAT24(macro, data)
# define REPEAT26(macro, data)  macro(26, data) REPEAT25(macro, data)
# define REPEAT27(macro, data)  macro(27, data) REPEAT26(macro, data)
# define REPEAT28(macro, data)  macro(28, data) REPEAT27(macro, data)
# define REPEAT29(macro, data)  macro(29, data) REPEAT28(macro, data)
# define REPEAT30(macro, data)  macro(30, data) REPEAT29(macro, data)
# define REPEAT31(macro, data)  macro(31, data) REPEAT30(macro, data)
# define REPEAT32(macro, data)  macro(32, data) REPEAT31(macro, data)
# define REPEAT33(macro, data)  macro(33, data) REPEAT32(macro, data)
# define REPEAT34(macro, data)  macro(34, data) REPEAT33(macro, data)
# define REPEAT35(macro, data)  macro(35, data) REPEAT34(macro, data)
# define REPEAT36(macro, data)  macro(36, data) REPEAT35(macro, data)
# define REPEAT37(macro, data)  macro(37, data) REPEAT36(macro, data)
# define REPEAT38(macro, data)  macro(38, data) REPEAT37(macro, data)
# define REPEAT39(macro, data)  macro(39, data) REPEAT38(macro, data)
# define REPEAT40(macro, data)  macro(40, data) REPEAT39(macro, data)
# define REPEAT41(macro, data)  macro(41, data) REPEAT40(macro, data)
# define REPEAT42(macro, data)  macro(42, data) REPEAT41(macro, data)
# define REPEAT43(macro, data)  macro(43, data) REPEAT42(macro, data)
# define REPEAT44(macro, data)  macro(44, data) REPEAT43(macro, data)
# define REPEAT45(macro, data)  macro(45, data) REPEAT44(macro, data)
# define REPEAT46(macro, data)  macro(46, data) REPEAT45(macro, data)
# define REPEAT47(macro, data)  macro(47, data) REPEAT46(macro, data)
# define REPEAT48(macro, data)  macro(48, data) REPEAT47(macro, data)
# define REPEAT49(macro, data)  macro(49, data) REPEAT48(macro, data)
# define REPEAT50(macro, data)  macro(50, data) REPEAT49(macro, data)
# define REPEAT51(macro, data)  macro(51, data) REPEAT50(macro, data)
# define REPEAT52(macro, data)  macro(52, data) REPEAT51(macro, data)
# define REPEAT53(macro, data)  macro(53, data) REPEAT52(macro, data)
# define REPEAT54(macro, data)  macro(54, data) REPEAT53(macro, data)
# define REPEAT55(macro, data)  macro(55, data) REPEAT54(macro, data)
# define REPEAT56(macro, data)  macro(56, data) REPEAT55(macro, data)
# define REPEAT57(macro, data)  macro(57, data) REPEAT56(macro, data)
# define REPEAT58(macro, data)  macro(58, data) REPEAT57(macro, data)
# define REPEAT59(macro, data)  macro(59, data) REPEAT58(macro, data)
# define REPEAT60(macro, data)  macro(60, data) REPEAT59(macro, data)
# define REPEAT61(macro, data)  macro(61, data) REPEAT60(macro, data)
# define REPEAT62(macro, data)  macro(62, data) REPEAT61(macro, data)
# define REPEAT63(macro, data)  macro(63, data) REPEAT62(macro, data)
# define REPEAT64(macro, data)  macro(64, data) REPEAT63(macro, data)

#endif // !REPEAT_MACRO_HH_
