#pragma once
#ifndef REPEAT_MACRO_HH_
# define REPEAT_MACRO_HH_


# define REPEAT(n, macro, data) REPEAT##n(macro, data)

# define REPEAT1(macro, data)	macro(1, data)
# define REPEAT2(macro, data)	REPEAT1(macro, data)	macro(2, data)
# define REPEAT3(macro, data)	REPEAT2(macro, data)	macro(3, data)
# define REPEAT4(macro, data)	REPEAT3(macro, data)	macro(4, data)
# define REPEAT5(macro, data)	REPEAT4(macro, data)	macro(5, data)
# define REPEAT6(macro, data)	REPEAT5(macro, data)	macro(6, data)
# define REPEAT7(macro, data)	REPEAT6(macro, data)	macro(7, data)
# define REPEAT8(macro, data)	REPEAT7(macro, data)	macro(8, data)
# define REPEAT9(macro, data)	REPEAT8(macro, data)	macro(9, data)
# define REPEAT10(macro, data)	REPEAT9(macro, data)	macro(10, data)
# define REPEAT11(macro, data)	REPEAT10(macro, data)	macro(11, data)
# define REPEAT12(macro, data)	REPEAT11(macro, data)	macro(12, data)
# define REPEAT13(macro, data)	REPEAT12(macro, data)	macro(13, data)
# define REPEAT14(macro, data)	REPEAT13(macro, data)	macro(14, data)
# define REPEAT15(macro, data)	REPEAT14(macro, data)	macro(15, data)
# define REPEAT16(macro, data)	REPEAT15(macro, data)	macro(16, data)
# define REPEAT17(macro, data)	REPEAT16(macro, data)	macro(17, data)
# define REPEAT18(macro, data)	REPEAT17(macro, data)	macro(18, data)
# define REPEAT19(macro, data)	REPEAT18(macro, data)	macro(19, data)
# define REPEAT20(macro, data)	REPEAT19(macro, data)	macro(20, data)
# define REPEAT21(macro, data)	REPEAT20(macro, data)	macro(21, data)
# define REPEAT22(macro, data)	REPEAT21(macro, data)	macro(22, data)
# define REPEAT23(macro, data)	REPEAT22(macro, data)	macro(23, data)
# define REPEAT24(macro, data)	REPEAT23(macro, data)	macro(24, data)
# define REPEAT25(macro, data)	REPEAT24(macro, data)	macro(25, data)
# define REPEAT26(macro, data)	REPEAT25(macro, data)	macro(26, data)
# define REPEAT27(macro, data)	REPEAT26(macro, data)	macro(27, data)
# define REPEAT28(macro, data)	REPEAT27(macro, data)	macro(28, data)
# define REPEAT29(macro, data)	REPEAT28(macro, data)	macro(29, data)
# define REPEAT30(macro, data)	REPEAT29(macro, data)	macro(30, data)
# define REPEAT31(macro, data)	REPEAT30(macro, data)	macro(31, data)
# define REPEAT32(macro, data)	REPEAT31(macro, data)	macro(32, data)
# define REPEAT33(macro, data)	REPEAT32(macro, data)	macro(33, data)
# define REPEAT34(macro, data)	REPEAT33(macro, data)	macro(34, data)
# define REPEAT35(macro, data)	REPEAT34(macro, data)	macro(35, data)
# define REPEAT36(macro, data)	REPEAT35(macro, data)	macro(36, data)
# define REPEAT37(macro, data)	REPEAT36(macro, data)	macro(37, data)
# define REPEAT38(macro, data)	REPEAT37(macro, data)	macro(38, data)
# define REPEAT39(macro, data)	REPEAT38(macro, data)	macro(39, data)
# define REPEAT40(macro, data)	REPEAT39(macro, data)	macro(40, data)
# define REPEAT41(macro, data)	REPEAT40(macro, data)	macro(41, data)
# define REPEAT42(macro, data)	REPEAT41(macro, data)	macro(42, data)
# define REPEAT43(macro, data)	REPEAT42(macro, data)	macro(43, data)
# define REPEAT44(macro, data)	REPEAT43(macro, data)	macro(44, data)
# define REPEAT45(macro, data)	REPEAT44(macro, data)	macro(45, data)
# define REPEAT46(macro, data)	REPEAT45(macro, data)	macro(46, data)
# define REPEAT47(macro, data)	REPEAT46(macro, data)	macro(47, data)
# define REPEAT48(macro, data)	REPEAT47(macro, data)	macro(48, data)
# define REPEAT49(macro, data)	REPEAT48(macro, data)	macro(49, data)
# define REPEAT50(macro, data)	REPEAT49(macro, data)	macro(50, data)
# define REPEAT51(macro, data)	REPEAT50(macro, data)	macro(51, data)
# define REPEAT52(macro, data)	REPEAT51(macro, data)	macro(52, data)
# define REPEAT53(macro, data)	REPEAT52(macro, data)	macro(53, data)
# define REPEAT54(macro, data)	REPEAT53(macro, data)	macro(54, data)
# define REPEAT55(macro, data)	REPEAT54(macro, data)	macro(55, data)
# define REPEAT56(macro, data)	REPEAT55(macro, data)	macro(56, data)
# define REPEAT57(macro, data)	REPEAT56(macro, data)	macro(57, data)
# define REPEAT58(macro, data)	REPEAT57(macro, data)	macro(58, data)
# define REPEAT59(macro, data)	REPEAT58(macro, data)	macro(59, data)
# define REPEAT60(macro, data)	REPEAT59(macro, data)	macro(60, data)
# define REPEAT61(macro, data)	REPEAT60(macro, data)	macro(61, data)
# define REPEAT62(macro, data)	REPEAT61(macro, data)	macro(62, data)
# define REPEAT63(macro, data)	REPEAT62(macro, data)	macro(63, data)
# define REPEAT64(macro, data)	REPEAT63(macro, data)	macro(64, data)

#endif // !REPEAT_MACRO_HH_
